### PR TITLE
Add staff messages

### PR DESCRIPTION
**Pull request by chrishanes**

### CODE REVIEW

**Comment by alan** [comment]
https://github.com/ministryofjustice/prison-visits-2/pull/477 needs to be merged and deployed before this PR

**Comment by mloughran** [comment]
Did all the VCR examples need to be re-recorded after messages were added? Doesn't make a big difference, but just a little untidy.

**Comment by alan** [comment]
Yes, they did. I believe is because of the different available dates.

**Comment by StupidCodeFactory** [comment]
@chrishanes can we close this?

**Comment by chrishanes** [comment]
I think we can @StupidCodeFactory

**Pull request closed without merging**
