### PR TITLE
[WIP] - GOVUK gem

### PR DESCRIPTION
**Pull request by StupidCodeFactory**

### CODE REVIEW

**Comment by alan** [comment]
What's the status with this PR @StupidCodeFactory ?

**Comment by StupidCodeFactory** [comment]
@alan this is waiting to adapt https://github.com/ministryofjustice/gov_uk_date_fields to active model We haven't got around to do that, it should be a rather easy change

**Comment by alan** [comment]
@StupidCodeFactory can we close this until it gets picked up again?

**Comment by StupidCodeFactory** [comment]
@alan It's not really my call to make

**Pull request closed without merging**
